### ISSUE TITLE
v1.1 does not work on Miyoo Mini Plus

### ISSUE THREAD

**Issue by rezwan737** [aweigit/freej2me-miyoomini#2]
Hi, v1.1 does not boot any jars, can you please also add v1.0 to the release. Thanks!

**Comment by qSHiSHp** [comment]
I have tried and it's run fine. You can try this:
`For anyone unable to launch the Jars. Copy the files manually from your PC using a card reader or something. FTP has issues.`

**Comment by rezwan737** [comment]
Hi Thanks for the response. It was an error on my end. v1.1 is working great on the latest OnionOS. There seem to be some issues with copying the JAVA folder to Miyoo via ftp with filezilla. Changing SD with a fresh OnionOS install was giving me the same error.

Then I decided to plug the sd with cardreader and copy the folder. Its working great now!

appreciate the hard work and huge fan of the project!
